export enum UserRole {
  ADMIN = "ADMIN",
  BORROWER = "BORROWER",
  SALES = "SALES",
  SANCTION = "SANCTION",
  DISBURSEMENT = "DISBURSEMENT",
  COLLECTION = "COLLECTION",
}

export enum EmploymentMode {
  SALARIED = "SALARIED",
  SELF_EMPLOYED = "SELF_EMPLOYED",
  UNEMPLOYED = "UNEMPLOYED",
}

export enum LoanStatus {
  LEAD = "LEAD",
  APPLIED = "APPLIED",
  SANCTIONED = "SANCTIONED",
  REJECTED = "REJECTED",
  DISBURSED = "DISBURSED",
  CLOSED = "CLOSED",
}

export enum DocumentType {
  SALARY_SLIP = "SALARY_SLIP",
}

export enum AuditAction {
  LOAN_APPLIED = "LOAN_APPLIED",
  LOAN_SANCTIONED = "LOAN_SANCTIONED",
  LOAN_REJECTED = "LOAN_REJECTED",
  LOAN_DISBURSED = "LOAN_DISBURSED",
  PAYMENT_RECORDED = "PAYMENT_RECORDED",
  LOAN_CLOSED = "LOAN_CLOSED",
}
